export const KEY = {
  a: "KeyA",
  b: "KeyB",
  c: "KeyC",
  d: "KeyD",
  e: "KeyE",
  f: "KeyF",
  g: "KeyG",
  h: "KeyH",
  i: "KeyI",
  j: "KeyJ",
  k: "KeyK",
  l: "KeyL",
  m: "KeyM",
  n: "KeyN",
  o: "KeyO",
  p: "KeyP",
  q: "KeyQ",
  r: "KeyR",
  s: "KeyS",
  t: "KeyT",
  u: "KeyU",
  v: "KeyV",
  w: "KeyW",
  x: "KeyX",
  y: "KeyY",
  z: "KeyZ",

  num0: "Digit0",
  num1: "Digit1",
  num2: "Digit2",
  num3: "Digit3",
  num4: "Digit4",
  num5: "Digit5",
  num6: "Digit6",
  num7: "Digit7",
  num8: "Digit8",
  num9: "Digit9",

  arrowUp: "ArrowUp",
  arrowDown: "ArrowDown",
  arrowLeft: "ArrowLeft",
  arrowRight: "ArrowRight",

  space: "Space",
  enter: "Enter",
  escape: "Escape",
  tab: "Tab",
  backspace: "Backspace",
  delete: "Delete",
  semicolon: "Semicolon",
  quote: "Quote",
  backquote: "Backquote",
  backslash: "Backslash",
  comma: "Comma",
  period: "Period",
  slash: "Slash",
  intlBackslash: "IntlBackslash",
  minus: "Minus",
  equal: "Equal",
  bracketLeft: "BracketLeft",
  bracketRight: "BracketRight",
  insert: "Insert",
  home: "Home",
  end: "End",
  pageUp: "PageUp",
  pageDown: "PageDown",
  capsLock: "CapsLock",
  contextMenu: "ContextMenu",
  printScreen: "PrintScreen",
  scrollLock: "ScrollLock",
  pause: "Pause",

  shiftLeft: "ShiftLeft",
  shiftRight: "ShiftRight",
  ctrlLeft: "ControlLeft",
  ctrlRight: "ControlRight",
  altLeft: "AltLeft",
  altRight: "AltRight",

  f1: "F1",
  f2: "F2",
  f3: "F3",
  f4: "F4",
  f5: "F5",
  f6: "F6",
  f7: "F7",
  f8: "F8",
  f9: "F9",
  f10: "F10",
  f11: "F11",
  f12: "F12",

  numpad0: "Numpad0",
  numpad1: "Numpad1",
  numpad2: "Numpad2",
  numpad3: "Numpad3",
  numpad4: "Numpad4",
  numpad5: "Numpad5",
  numpad6: "Numpad6",
  numpad7: "Numpad7",
  numpad8: "Numpad8",
  numpad9: "Numpad9",
  numpadAdd: "NumpadAdd",
  numpadSubtract: "NumpadSubtract",
  numpadMultiply: "NumpadMultiply",
  numpadDivide: "NumpadDivide",
  numpadDecimal: "NumpadDecimal",
  numpadEnter: "NumpadEnter",
  numLock: "NumLock",
} as const;
export type KeyCode = (typeof KEY)[keyof typeof KEY];

export const KEY_GROUP = {
  shift: [KEY.shiftLeft, KEY.shiftRight],
  ctrl: [KEY.ctrlLeft, KEY.ctrlRight],
  alt: [KEY.altLeft, KEY.altRight],
} as const;
