export const KEY = {
  a: "KeyA",
  b: "KeyB",
  c: "KeyC",
  d: "KeyD",
  e: "KeyE",
  f: "KeyF",
  g: "KeyG",
  h: "KeyH",
  i: "KeyI",
  j: "KeyJ",
  k: "KeyK",
  l: "KeyL",
  m: "KeyM",
  n: "KeyN",
  o: "KeyO",
  p: "KeyP",
  q: "KeyQ",
  r: "KeyR",
  s: "KeyS",
  t: "KeyT",
  u: "KeyU",
  v: "KeyV",
  w: "KeyW",
  x: "KeyX",
  y: "KeyY",
  z: "KeyZ",

  num0: "Digit0",
  num1: "Digit1",
  num2: "Digit2",
  num3: "Digit3",
  num4: "Digit4",
  num5: "Digit5",
  num6: "Digit6",
  num7: "Digit7",
  num8: "Digit8",
  num9: "Digit9",

  arrowUp: "ArrowUp",
  arrowDown: "ArrowDown",
  arrowLeft: "ArrowLeft",
  arrowRight: "ArrowRight",

  space: "Space",
  enter: "Enter",
  escape: "Escape",
  tab: "Tab",
  backspace: "Backspace",
  delete: "Delete",

  minus: "Minus",
  equal: "Equal",
  bracketLeft: "BracketLeft",
  bracketRight: "BracketRight",

  shiftLeft: "ShiftLeft",
  shiftRight: "ShiftRight",
  ctrlLeft: "ControlLeft",
  ctrlRight: "ControlRight",
  altLeft: "AltLeft",
  altRight: "AltRight",

  f1: "F1",
  f2: "F2",
  f3: "F3",
  f4: "F4",
  f5: "F5",
  f6: "F6",
} as const;
export type KeyCode = (typeof KEY)[keyof typeof KEY];

export const KEY_GROUP = {
  shift: [KEY.shiftLeft, KEY.shiftRight],
  ctrl: [KEY.ctrlLeft, KEY.ctrlRight],
  alt: [KEY.altLeft, KEY.altRight],
} as const;
